### ISSUE TITLE
EnhancedComboBox component does not support Qt 5.14

### ISSUE THREAD

**Issue by darrellenns** [ChrisTerBeke/ThingiBrowser#37] opened 2020-04-29 23:53 UTC
When I do Extensions->ThingiBrowser->Open, the ThingiBrowser dialog does not open (nothing happens). This is with Cura 4.5.0 and ThingiBrowser 2.0.0. Prior to the 2.0.0 update and Thingiverse redesign, it was working fine.

The console shows following:
```
QQmlComponent: Component is not ready
2020-04-29 16:48:55,679 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [559]: file:///home/denns/.local/share/cura/4.5/plugins/ThingiBrowser/ThingiBrowser/views/Thingiverse.qml:33:5: Type ThingiMain unavailable
2020-04-29 16:48:55,679 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [559]: file:///home/denns/.local/share/cura/4.5/plugins/ThingiBrowser/ThingiBrowser/views/ThingiMain.qml:15:5: Type ThingiHeader unavailable
2020-04-29 16:48:55,680 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [559]: file:///home/denns/.local/share/cura/4.5/plugins/ThingiBrowser/ThingiBrowser/views/ThingiHeader.qml:12:5: Type ServiceSelector unavailable
2020-04-29 16:48:55,680 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [559]: file:///home/denns/.local/share/cura/4.5/plugins/ThingiBrowser/ThingiBrowser/views/ServiceSelector.qml:4:1: Type EnhancedComboBox unavailable
2020-04-29 16:48:55,681 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [559]: file:///home/denns/.local/share/cura/4.5/plugins/ThingiBrowser/ThingiBrowser/views/EnhancedComboBox.qml:9:5: Cannot override FINAL property
2020-04-29 16:48:55,681 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]: Exception: Failed to activate the menu item
2020-04-29 16:48:55,682 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]: Traceback (most recent call last):
2020-04-29 16:48:55,683 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]:   File "/usr/lib/python3.8/site-packages/UM/Qt/Bindings/ExtensionModel.py", line 54, in subMenuTriggered
2020-04-29 16:48:55,683 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]:     item["extension"].activateMenuItem(option_name)
2020-04-29 16:48:55,684 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]:   File "/usr/lib/python3.8/site-packages/UM/Extension.py", line 38, in activateMenuItem
2020-04-29 16:48:55,684 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]:     self._menu_function_dict[name]()
2020-04-29 16:48:55,684 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]:   File "/home/denns/.local/share/cura/4.5/plugins/ThingiBrowser/ThingiBrowser/ThingiBrowser/ThingiBrowserExtension.py", line 44, in showMainWindow
2020-04-29 16:48:55,685 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]:     self._main_dialog = self._createComponent("Thingiverse.qml")
2020-04-29 16:48:55,685 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]:   File "/home/denns/.local/share/cura/4.5/plugins/ThingiBrowser/ThingiBrowser/ThingiBrowser/ThingiBrowserExtension.py", line 84, in _createComponent
2020-04-29 16:48:55,685 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]:     raise Exception("Failed to create Thingiverse dialog")
2020-04-29 16:48:55,686 - WARNING - [MainThread] UM.Qt.Bindings.ExtensionModel.subMenuTriggered [58]: Exception: Failed to create Thingiverse dialog
```

**Comment by ChrisTerBeke** [comment] 2020-04-30 08:33
The error of significance here seems to be `2020-04-29 16:48:55,681 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [559]: file:///home/denns/.local/share/cura/4.5/plugins/ThingiBrowser/ThingiBrowser/views/EnhancedComboBox.qml:9:5: Cannot override FINAL property`. However I cannot reproduce it locally. Do you have another version of Qt installed on your machine?

**Comment by darrellenns** [comment] 2020-04-30 16:09
I have QT 5.14.2. This is on up to date Arch Linux. I tested with another machine (also running Arch), and it has the same issue.

**Comment by darrellenns** [comment] 2020-04-30 18:55
It looks like this error may be caused by a naming conflict between a custom QML property and one that is already in QT. See here for an example of someone having a similar issue: https://bugreports.qt.io/browse/QTBUG-7948

According to https://doc.qt.io/qt-5/qml-qtquick-controls2-combobox.html, currentValue and valueRole were added to ComboBox in QT 5.14. However, it looks like you are also adding those same properties in EnhancedComboBox.qml. I assume these are FINAL properties in QT, which means they can't be overridden.

Possible fixes:
- Rename the custom currentValue and valueRole properties
- Detect if QT 5.14+ is used. If so, use the built in ComboBox instead of the custom one.

**Comment by darrellenns** [comment] 2020-04-30 18:59
As a confirmation/test, I commented out most of EnhancedComboBox.qml, leave just the following:

```
import QtQuick 2.2
import QtQuick.Controls 2.0
import QtQuick.Layouts 1.3

ComboBox
{
    id: comboBox
}
```
This does work on my system (but would obviously break with QT<5.14).

**Comment by ChrisTerBeke** [comment] 2020-05-01 12:02
To my knowledge Cura ships with Qt 5.10, so a bug caused by using Qt 5.14 is a bit out of scope for me. However renaming the FINAL properties should not be much a problem, so I'll look into that.

**Closed** 2020-05-01 17:33 UTC
Labels: enhancement
